### ISSUE TITLE
can response data with return 400/404/500  be verified

### ISSUE THREAD

**Issue by forumbyr** [peritus/robotframework-httplibrary#26]
if response is 400/404/500, does response data  support normal key words, eg : 'Should Contain' ?
I found it not supports now, it will fail soon if return status >=400  .
will you add this feature?
Thanks

**Comment by peritus** [comment]
1) You can use the 'Next Request ...' family of keywords (documented at http://peritus.github.io/robotframework-httplibrary/HttpLibrary.html) to make expectations about the next request. Making failing requests fail the test as a default is just a convenience, because most of the time that's what you want.
2) You can the 'Get Response Status' keyword to get the response status code and then make your own assertions.

HTH

**Comment by forumbyr** [comment]
sorry for not seen this : Next Request May Not Succeed, and it works fine!
Thanks !

**Comment by forumbyr** [comment]
I have another quersion: 
does httplibrary support unicode ? 
eg, test with : 
GET     /query?q=sälen  
or:
GET     /query?q=s中国
both will fail , error is :
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 30: ordinal not in range(128)
Thanks 

---

and i found this :https://github.com/peritus/robotframework-httplibrary/issues/21
maybe url also could be encoded before call http method?

**Comment by Swati3027** [comment]
How to get the response message of a 400 response?
suppose , i am getting a error msg - "xyz is not present" along with a 400 status code.
How can i fetch this message?
